/**
 * API and application constants
 *
 * Custom field IDs, workflow statuses, and option mappings are loaded from
 * productive.config.json (generated by `npm run setup`). If the config file
 * is missing, the server still works - you just won't be able to set task
 * types, priorities, or workflow statuses.
 */

import { readFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

// ---------------------------------------------------------------------------
// Load config from productive.config.json
// ---------------------------------------------------------------------------

interface ProductiveConfig {
  custom_field_ids?: {
    task_type?: string;
    priority?: string;
    estimate?: string;
    labels?: string;
  };
  task_type_options?: Record<string, string>;
  priority_options?: Record<string, string>;
  label_options?: Record<string, string>;
  workflow_status_names?: string[];
  workflow_status_ids?: Record<string, string>;
  /** Workflow each configured status belongs to, keyed by status name. */
  workflow_status_workflows?: Record<string, string>;
  /** The workflow most of this organisation's tasks actually use. */
  dominant_workflow?: { id: string; name: string };
}

function loadConfig(): ProductiveConfig {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);
  // Config file lives in project root (one level up from src/ or dist/)
  const configPath = join(__dirname, "..", "productive.config.json");

  if (!existsSync(configPath)) {
    console.error(
      "[Config] productive.config.json not found - run 'npm run setup' to auto-configure",
    );
    return {};
  }

  try {
    const raw = readFileSync(configPath, "utf-8");
    const config = JSON.parse(raw) as ProductiveConfig;
    console.error("[Config] Loaded productive.config.json");
    return config;
  } catch (err) {
    console.error(
      `[Config] Failed to parse productive.config.json: ${err instanceof Error ? err.message : err}`,
    );
    return {};
  }
}

const config = loadConfig();

// ---------------------------------------------------------------------------
// API constants
// ---------------------------------------------------------------------------

export const API_URL = "https://api.productive.io/api/v2";
export const CHARACTER_LIMIT = 25000;

// Rate limit configuration
export const RATE_LIMIT_REQUESTS = 100;
export const RATE_LIMIT_WINDOW_MS = 10000; // 10 seconds

// Additional rate limit (not enforced in this implementation, but documented)
export const RATE_LIMIT_EXTENDED_REQUESTS = 4000;
export const RATE_LIMIT_EXTENDED_WINDOW_MS = 1800000; // 30 minutes

// ---------------------------------------------------------------------------
// Task type and priority labels
// ---------------------------------------------------------------------------

const defaultTaskTypes = [
  "Bug",
  "Task",
  "Feature",
  "Question",
  "Meeting",
  "Test Case",
] as const;

const defaultPriorities = [
  "Highest",
  "High",
  "Medium",
  "Low",
  "Lowest",
] as const;

export const TASK_TYPES = defaultTaskTypes;
export const PRIORITIES = defaultPriorities;

// ---------------------------------------------------------------------------
// Custom field IDs (loaded from config)
// ---------------------------------------------------------------------------

export const CUSTOM_FIELD_IDS = {
  TASK_TYPE: config.custom_field_ids?.task_type || "",
  PRIORITY: config.custom_field_ids?.priority || "",
  ESTIMATE: config.custom_field_ids?.estimate || "",
  LABELS: config.custom_field_ids?.labels || "",
} as const;

// ---------------------------------------------------------------------------
// Custom field option ID mappings (loaded from config)
// ---------------------------------------------------------------------------

// Build TASK_TYPE_OPTIONS from config, falling back to empty strings
const taskTypeOpts: Record<string, string> = config.task_type_options || {};
export const TASK_TYPE_OPTIONS: Record<(typeof TASK_TYPES)[number], string> = {
  Bug: taskTypeOpts["Bug"] || "",
  Task: taskTypeOpts["Task"] || "",
  Feature: taskTypeOpts["Feature"] || "",
  Question: taskTypeOpts["Question"] || "",
  Meeting: taskTypeOpts["Meeting"] || "",
  "Test Case": taskTypeOpts["Test Case"] || "",
};

// Build PRIORITY_OPTIONS from config, falling back to empty strings
const priorityOpts: Record<string, string> = config.priority_options || {};
export const PRIORITY_OPTIONS: Record<(typeof PRIORITIES)[number], string> = {
  Highest: priorityOpts["Highest"] || "",
  High: priorityOpts["High"] || "",
  Medium: priorityOpts["Medium"] || "",
  Low: priorityOpts["Low"] || "",
  Lowest: priorityOpts["Lowest"] || "",
};

// Build LABEL_OPTIONS from config (mutable — new labels can be added at runtime)
export const LABEL_OPTIONS: Record<string, string> = {
  ...(config.label_options || {}),
};

// ---------------------------------------------------------------------------
// Task dependency type constants (standard Productive API values)
// ---------------------------------------------------------------------------

export const DEPENDENCY_TYPES = ["blocking", "waiting_on", "related"] as const;

export const DEPENDENCY_TYPE_IDS: Record<
  (typeof DEPENDENCY_TYPES)[number],
  number
> = {
  blocking: 1,
  waiting_on: 2,
  related: 3,
};

export const DEPENDENCY_TYPE_NAMES: Record<
  number,
  (typeof DEPENDENCY_TYPES)[number]
> = {
  1: "blocking",
  2: "waiting_on",
  3: "related",
};

// ---------------------------------------------------------------------------
// Workflow statuses (loaded from config)
// ---------------------------------------------------------------------------

// Use discovered status names if available, otherwise fall back to common defaults
const configStatusNames = config.workflow_status_names || [];
export const WORKFLOW_STATUSES = (
  configStatusNames.length > 0
    ? configStatusNames
    : [
        "To Do",
        "Backlog",
        "In Progress",
        "Blocked",
        "In Review",
        "Ready for Testing",
        "Ready for Deployment",
        "To Be Discussed",
        "Done / Closed",
        "Obsolete / Won't Fix",
        "Closed",
      ]
) as readonly string[];

export const WORKFLOW_STATUS_IDS: Record<string, string> =
  config.workflow_status_ids || {};

/** Workflow each configured status belongs to, keyed by status name. */
export const WORKFLOW_STATUS_WORKFLOWS: Record<string, string> =
  config.workflow_status_workflows || {};

/**
 * Resolve a workflow status name to its Productive ID.
 *
 * Throws rather than silently skipping the field — a task created with the
 * wrong status while the tool reports success is worse than a clear failure.
 *
 * Note that Productive scopes statuses to a workflow, so a status configured
 * against one workflow is rejected by the API on tasks belonging to another.
 * `npm run setup` resolves duplicate names in favour of the workflow your
 * tasks actually use, and warns about the ones it cannot.
 */
export function resolveWorkflowStatusId(name: string): string {
  const statusId = WORKFLOW_STATUS_IDS[name];
  if (statusId) {
    return statusId;
  }

  const available = Object.keys(WORKFLOW_STATUS_IDS);
  if (available.length === 0) {
    throw new Error(
      `Workflow status "${name}" cannot be resolved because no statuses are configured. ` +
        `Run \`npm run setup\` to discover your organisation's workflow statuses.`,
    );
  }

  throw new Error(
    `Workflow status "${name}" is not configured. Available statuses: ${available.join(", ")}. ` +
      `If you expected "${name}" to exist, re-run \`npm run setup\` — it may have been added since the config was generated.`,
  );
}
